"""add password reset fields

Revision ID: d52eca7bfb14
Revises: 8bc8bc347b81
Create Date: 2026-08-13 19:11:46.978912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52eca7bfb14'
down_revision: Union[str, Sequence[str], None] = '8bc8bc347b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token_expires')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
